"""empty message

Revision ID: 684d27632afd
Revises: 91bee87336a9
Create Date: 2023-01-17 01:27:17.470822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '684d27632afd'
down_revision = '91bee87336a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters', sa.String(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('director', sa.String(length=150), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.String(length=500), nullable=False),
    sa.Column('planets', sa.String(length=550), nullable=False),
    sa.Column('producer', sa.String(length=150), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(length=500), nullable=False),
    sa.Column('starships', sa.String(length=550), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('vehicles', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MGLT', sa.String(length=150), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=False),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('pilots', sa.String(length=150), nullable=False),
    sa.Column('starship_class', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eye_colors', sa.String(length=120), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('hair_colors', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('skin_color', sa.String(length=150), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('species', sa.String(length=500), nullable=False),
    sa.Column('starships', sa.String(length=900), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('vehicles', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_lifespan', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('eye_colors', sa.String(length=120), nullable=False),
    sa.Column('hair_colors', sa.String(length=120), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('people', sa.String(length=900), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('skin_colors', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('pilots', sa.String(length=500), nullable=False),
    sa.Column('films', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('vehicle_class', sa.String(length=150), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('films', sa.String(length=800), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('residents', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=900), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('url')
        batch_op.drop_column('terrain')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('residents')
        batch_op.drop_column('population')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('films')
        batch_op.drop_column('edited')
        batch_op.drop_column('diameter')
        batch_op.drop_column('created')

    op.drop_table('vehicles')
    op.drop_table('species')
    op.drop_table('people')
    op.drop_table('starships')
    op.drop_table('films')
    # ### end Alembic commands ###
